/**
 * A bank's own index file, written by the host.
 *
 * Cortex kept an `INDEX.md` — one line per project with its status, its
 * summary and the path to open next — generated by a script in the bank and
 * checked by a CI that was never wired up, so every memory landed by an agent
 * left it a line out of date. A manifest bank can now say
 * `index: { file: INDEX.md, generate: true }` and the host writes the file
 * itself on every landing, from what is actually there: the docs the
 * manifest's `docs` glob names (entry points, handoffs, plans), grouped by
 * the first scope label, each with the frontmatter it carries and a count of
 * the memories, decisions and companions beside it. Docs outside the scoped
 * tree — a `reference/` folder — are listed last as cross-cutting facts.
 *
 * Deterministic but for the date on the first line, which is what lets a
 * reader ignore the header and compare the rest.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';

import { parseFrontmatter } from './frontmatter.js';
import { listFiles } from './glob.js';
import type { Bank } from './model.js';

interface DocLine {
  readonly group: string;
  readonly label: string;
  readonly path: string;
  readonly dir: string;
  readonly status: string | null;
  readonly summary: string | null;
  readonly memories: number;
  readonly decisions: number;
  readonly companions: readonly string[];
}

const ENTRY_POINTS = new Set(['PROJECT.md', 'SYSTEM.md', 'README.md']);
const COMPANIONS = ['HANDOFF.md', 'PLAN.md'];

function text(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value.trim() : null;
}

function dirOf(path: string): string {
  const at = path.lastIndexOf('/');
  return at === -1 ? '' : path.slice(0, at);
}

/** Render the index for a bank as it stands. `null` when the bank keeps no generated index. */
export function renderBankIndexFile(bank: Bank, today: string = new Date().toISOString().slice(0, 10)): string | null {
  if (!bank.indexGenerated || bank.indexFile === null) return null;
  const docs = bank.docGlobs.length > 0 ? listFiles(bank.root, bank.docGlobs) : [];
  const entryPoints = docs.filter((path) => ENTRY_POINTS.has(path.split('/').at(-1) ?? ''));
  const others = docs.filter((path) => !ENTRY_POINTS.has(path.split('/').at(-1) ?? '') && !COMPANIONS.includes(path.split('/').at(-1) ?? ''));
  const lines: DocLine[] = [];
  for (const path of entryPoints) {
    const dir = dirOf(path);
    const scope = bank.memories.scopeOfDirectory(dir);
    const labels = bank.memories.levels.map((level) => scope[level]).filter((value): value is string => value !== undefined);
    let data: Readonly<Record<string, unknown>> | null = null;
    try {
      data = parseFrontmatter(readFileSync(join(bank.root, path), 'utf8')).data;
    } catch {
      data = null;
    }
    const prefix = dir.length === 0 ? '' : `${dir}/`;
    const companions = COMPANIONS.filter((name) => docs.includes(`${prefix}${name}`)).map((name) => name.replace('.md', ''));
    lines.push({
      group: labels[0] ?? 'reference',
      label: labels.length > 0 ? labels.join('/') : dir || path,
      path,
      dir,
      status: data === null ? null : text(data['status']),
      summary: data === null ? null : (text(data['summary']) ?? text(data['description'])),
      memories: bank.entries.filter((entry) => entry.problems.length === 0 && (dir.length === 0 || entry.file.startsWith(`${dir}/`))).length,
      decisions: docs.filter((other) => other.startsWith(`${prefix}decisions/`)).length + listFiles(bank.root, [`${prefix}decisions/*.md`]).length,
      companions,
    });
  }
  // Decisions are counted from the tree rather than the docs glob, so the two
  // sources above are deduplicated here.
  const seenDecisions = new Set<string>();
  for (const line of lines) {
    const inTree = listFiles(bank.root, [`${line.dir.length === 0 ? '' : `${line.dir}/`}decisions/*.md`]);
    for (const path of inTree) seenDecisions.add(path);
  }

  const groups = new Map<string, DocLine[]>();
  for (const line of lines) {
    const bucket = groups.get(line.group) ?? [];
    bucket.push(line);
    groups.set(line.group, bucket);
  }
  const out: string[] = [
    `# ${bank.name.toUpperCase()} INDEX - generated ${today} by Artemis memory banks. Do not edit.`,
    '',
    'Read this, open the entry point of the area you are working on, then its',
    'HANDOFF.md. Copy paths verbatim. The contract for reading and writing here is',
    `in ${bank.instructions === null ? 'README.md' : 'BANK.md'}.`,
    '',
  ];
  for (const group of [...groups.keys()].filter((key) => key !== 'reference').sort()) {
    out.push(`## ${group}`);
    for (const line of (groups.get(group) ?? []).sort((a, b) => a.label.localeCompare(b.label))) {
      const bits = [`**${line.status ?? '?'}**`, line.summary ?? '(no summary)'];
      const tail: string[] = [];
      if (line.companions.length > 0) tail.push(line.companions.join('+'));
      const decisions = listFiles(bank.root, [`${line.dir.length === 0 ? '' : `${line.dir}/`}decisions/*.md`]).length;
      if (decisions > 0) tail.push(`${String(decisions)} decisions`);
      if (line.memories > 0) tail.push(`${String(line.memories)} memories`);
      const suffix = tail.length > 0 ? ` (${tail.join(', ')})` : '';
      out.push(`- ${line.label} - ${bits.join(' - ')} -> ${line.path}${suffix}`);
    }
    out.push('');
  }
  const reference = [...(groups.get('reference') ?? []).map((line) => ({ path: line.path, summary: line.summary })), ...others.map((path) => {
    let data: Readonly<Record<string, unknown>> | null = null;
    try {
      data = parseFrontmatter(readFileSync(join(bank.root, path), 'utf8')).data;
    } catch {
      data = null;
    }
    return { path, summary: data === null ? null : (text(data['summary']) ?? text(data['description'])) };
  })].sort((a, b) => a.path.localeCompare(b.path));
  if (reference.length > 0) {
    out.push('## reference (cross-cutting facts)');
    for (const item of reference) out.push(`- ${item.path}${item.summary === null ? '' : ` - ${item.summary}`}`);
    out.push('');
  }
  return `${out.join('\n')}\n`;
}
